plugins {
    id 'java-library'
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = "${mc_version}-${mod_version}"
group = 'moe.box.mc.colonyward'
base {
    archivesName = 'colonyward'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

runs {
    client {
        workingDirectory project.file('run')
        systemProperty 'neoforge.logging.markers', 'REGISTRIES'
        systemProperty 'neoforge.logging.console.level', 'debug'
        modSource sourceSets.main
    }

    server {
        workingDirectory project.file('run')
        systemProperty 'neoforge.logging.markers', 'REGISTRIES'
        systemProperty 'neoforge.logging.console.level', 'debug'
        modSource sourceSets.main
    }
}

repositories {
    mavenCentral()
    maven {
        name 'MineColonies'
        url 'https://ldtteam.jfrog.io/ldtteam/modding'
        content {
            includeGroup 'com.ldtteam'
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    implementation "com.ldtteam:minecolonies:${colony_version}"
    implementation "com.ldtteam:structurize:${structurize_version}"
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : "colonyward",
            "Specification-Vendor"    : "Box.moe, RomDmitriy",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : "${version}",
            "Implementation-Vendor"   : "Box.moe, RomDmitriy",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
